package sar.html.warning;

public enum WarnType {
	NO_CHILDREN,
	NO_BROTHERS_ROOT,
	NO_BROTHERS_NORMAL,
	CANNOT_MOVE_ROOT,
	CANNOT_MOVE_ONLY,
	CANNOT_MOVE_TOP,
	CANNOT_MOVE_BOTTOM,
	NO_ATTRIBUTES,
	ATTRIBUTE_NOT_FOUND,
	IS_SINGLED,
	IS_COUPLED,
	WILL_BE_CLEARED;
}
